### ISSUE TITLE
Form submit not working with jq 1.7.2

### ISSUE THREAD

**Issue by wallenium** [jquery-form/form#219]
Updated jquery from 1.7.1 to 1.7.2, and the forms are not working any longer. is that error known?

TypeError: options.type.toUpperCase is not a function

Same with the 1.8rc1

**Comment by malsup** [comment]
Definitely not a known error.  Do you have that problem on the test suite?  

http://jquery.malsup.com/form/test/

**Comment by wallenium** [comment]
no. thats working fine. no error.
i have it in my working system (using your plugin in eqdkpplus for comments, if you know that project. tried to update to 1.7.2 and did not work. not sure why.)

**Comment by randawilly** [comment]
Hi,
i have the same error when i use .ajaxForm() with jquery 
and form submit doesn't work:

$("#preview_infos_logo").html('<img src="'+base_url_visurba+'application/resources/front/images/wait.gif" alt="Uploading...."/>');
                $("#edit_infos_user_logo_form").ajaxForm(
                {
                    target: '#preview_infos_logo'
                }).submit();

with your link, i have :
"NetworkError: 404 Not Found - http://jquery.malsup.com/form/test/bogus.php"

i tried jquery 1.7, 1.7.2 , 1.8.2 with the same result

wallenium> have you solved your pbm

**Comment by wallenium** [comment]
no. I haven't. strange Problem. Staying on 1.7.1 atm, but should be fixed soon.

**Comment by wallenium** [comment]
randawilly: could you upload a nonworking sample on http://jsbin.com/? I think its easier to debug if he has a sample

**Comment by randawilly** [comment]
it is only now that I come back to the topic, sorry.
the code doesn't load on http://jsbin.com/, many combination js-php.
I used the code here: http://stackoverflow.com/questions/8484660/upload-an-image-without-refreshing-page-in-php 
but on my site I already use a lot of plugins jquery and other javascript combination, I think it's coming from there, but I'm still looking.

**Comment by luzat** [comment]
I can confirm the issue with jQuery 1.8.2. The problem seems to be the usage of attr (vs. prop) for determining action and method. I've submitted [PR 240](https://github.com/malsup/form/pull/240) which fixes the issue in my case where dynamically generated forms are used.

**Comment by malsup** [comment]
Can someone post a link to a page that demonstrates the problem?  Attr should be perfectly valid for access the method and action properties.

**Comment by luzat** [comment]
I will try to make a test case available, but this may take some weeks.

**Comment by randawilly** [comment]
thank you luzat, it works fine for me with jquery 1.8.2, it solved all my problem :-) :+1:
